#!/bin/sh

expanded_queries_dir=expanded-queries/trec678

parallel --line-buffer --tag -j$1 'python run_ap_generator.py {}' ::: $expanded_queries_dir/rm3/weights/* \
  $expanded_queries_dir/spl/weights/* \
  $expanded_queries_dir/ceqe/weights/* \
  $expanded_queries_dir/loglogistic/weights/*
